# Compute nodes

compute-1.example.com:
  bmc_user: root
  bmc_password: "p4ssw0rd!"
  power_type: ipmi
  bmc_address: 192.168.200.1
  bmc_power_boot_type: efi
  zone: AZ1
  tags: ["gpu", "compute", "compute-1"]

compute-2.example.com:
  bmc_user: root
  bmc_password: "p4ssw0rd!"
  power_type: ipmi
  bmc_address: 192.168.200.2
  bmc_power_boot_type: efi
  zone: AZ2
  tags: ["gpu", "compute", "compute-2"]

compute-3.example.com:
  bmc_user: root
  bmc_password: "p4ssw0rd!"
  power_type: ipmi
  bmc_address: 192.168.200.3
  bmc_power_boot_type: efi
  zone: AZ3
  tags: ["gpu", "compute", "compute-3"]

compute-4.example.com:
  bmc_user: root
  bmc_password: "p4ssw0rd!"
  power_type: ipmi
  bmc_address: 192.168.200.4
  bmc_power_boot_type: efi
  zone: AZ1
  tags: ["gpu", "compute", "compute-4"]

compute-5.example.com:
  bmc_user: root
  bmc_password: "p4ssw0rd!"
  power_type: ipmi
  bmc_address: 192.168.200.5
  bmc_power_boot_type: efi
  zone: AZ2
  tags: ["gpu", "compute", "compute-5"]

compute-6.example.com:
  bmc_user: root
  bmc_password: "p4ssw0rd!"
  power_type: ipmi
  bmc_address: 192.168.200.6
  bmc_power_boot_type: efi
  zone: AZ3
  tags: ["gpu", "compute", "compute-6"]

# Control and Storage nodes

control-storage-1.example.com:
  bmc_user: root
  bmc_password: "p4ssw0rd!"
  power_type: ipmi
  bmc_address: 192.168.200.7
  bmc_power_boot_type: efi
  zone: AZ1
  tags: ["no-nvme-multipath", "control-storage", "control-storage-1"]

control-storage-2.example.com:
  bmc_user: root
  bmc_password: "p4ssw0rd!"
  power_type: ipmi
  bmc_address: 192.168.200.8
  bmc_power_boot_type: efi
  zone: AZ2
  tags: ["no-nvme-multipath", "control-storage", "control-storage-2"]

control-storage-3.example.com:
  bmc_user: root
  bmc_password: "p4ssw0rd!"
  power_type: ipmi
  bmc_address: 192.168.200.9
  bmc_power_boot_type: efi
  zone: AZ3
  tags: ["no-nvme-multipath", "control-storage", "control-storage-3"]

network-1.example.com:
  bmc_user: root
  bmc_password: "include-rel://secrets/bmc-password.txt"
  power_type: ipmi
  bmc_address: 192.168.200.10
  bmc_power_boot_type: efi
  zone: AZ1
  tags: ["network", "network-1"]
